---
- name: NFS package installation
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create shared folders
  file:
    path: "{{item}}"
    state: directory
  loop: "{{ shared_dir }}"

- name: Setup of ownership and mode
  file:
    path: "{{ item }}"
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{ shared_dir }}"

- name: Configure NFS export file
  lineinfile:
    path: /etc/exports
    line: |
      {{ shared_dir[0] }} {{hostvars['controlplane'].private_ip}}(rw,sync,all_squash,anonuid={{mysql_uid}},anongid={{mysql_gid}},no_subtree_check) {{hostvars['worker01'].private_ip}}(rw,sync,all_squash,anonuid={{mysql_uid}},anongid={{mysql_gid}},no_subtree_check)
      {{ shared_dir[1] }} {{hostvars['controlplane'].private_ip}}(rw,sync,no_root_squash,no_subtree_check) {{hostvars['worker01'].private_ip}}(rw,sync,no_root_squash,no_subtree_check)
    insertafter: EOF
    state: present

- name: Activate the NFS configuration
  command: exportfs -a

- name: Starting NFS server
  service:
    name: nfs-server
    state: started
    enabled: yes
