---
- name: Pull docker image
  hosts: test
  become: true
  tasks:
    - name: Pull the webapp image
      docker_image: 
        name: tomgfr/webapp:latest
        source: pull

    - name: Run the webapp container
      docker_container:
        name: webapp-test
        image: tomgfr/webapp:latest
        state: started
        pull: true    # makes sure the image is always downloaded
        ports:
          - "80:80"