---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: production
  labels:
    app: db
spec:
  containers:
    - name: db
      image: mysql:5.7
      env:
        - name: MYSQL_DATABASE
          value: dbname
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mysql-pvc
