---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: production
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext: # 999 ==> uid of user systemd-coredump (mysql)
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: wp-database
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: userpwd
            - name: MYSQL_ROOT_PASSWORD # rootpwd
              valueFrom:
                secretKeyRef:
                  name: db-secret # refers to the name of the secret
                  key: rootpwd # one of the keys of the secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-pvc
