---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-secret
#   namespace: production
# data:
#   .dockerconfigjson: to_be_replaced # value to be replaced by the result of cat .dockerconfig.json | base64 (.dockerconfig.json created by the command docker login)
# type: kubernetes.io/dockerconfigjson

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: production
data:
  userpwd: YXUgcmV2b2ly
  rootpwd: Ym9uam91cg==
