---
# WordPress Application

apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: wp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: production
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306

---
# Thomas webpage
apiVersion: v1
kind: Service
metadata:
  name: webpage-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: webpage
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
