---
# WordPress Application

apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: production
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
# Thomas webpage
apiVersion: v1
kind: Service
metadata:
  name: webpage-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: webpage
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
