---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: production
spec:
  accessModes:
    - ReadWriteMany # or ReadOnlyMany or ReadWriteMany
  hostPath:
    path: /data/
    type: DirectoryOrCreate

  capacity:
    storage: 1Gi
  # hostPath:
  #   path: /tmp/data # not to be used in a production environment (because of multiple hosts)

  persistentVolumeReclaimPolicy: Retain # it is retained by default if the PVC is deleted, or Delete, or Recycle
