---
# MYSQL

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
spec:
  selector:
    matchLabels:
      storage: mysql-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: production
  labels:
    storage: mysql-storage
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # or ReadOnlyMany or ReadWriteMany
  nfs:
    path: /mnt/mysql
    server: nfs_ip_tbc
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle # it is retained by default if the PVC is deleted, or Delete, or Recycle

---
# WORDPRESS

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: production
spec:
  selector:
    matchLabels:
      storage: wordpress-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: production
  labels:
    storage: wordpress-storage
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # or ReadOnlyMany or ReadWriteMany
  #  storageClassName: ebs-storage-class
  nfs:
    path: /mnt/wordpress
    server: nfs_ip_tbc
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle # it is retained by default if the PVC is deleted, or Delete, or Recycle
