---
# WordPress application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      # securityContext: # 33 ==> uid of user www-data (wordpress)
      #   fsGroup: 33
      #   # runAsUser: 33
      #   # runAsGroup: 33
      # not possible to set uid 33 because of apache 80 privileged port which needs root...

      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-svc
            - name: WORDPRESS_DB_NAME
              value: wp-database
            - name: WORDPRESS_DB_USER
              value: user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: userpwd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress-pvc
