---
- name: Installation of pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Installation of PyYAML
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - pyyaml
    - openshift
